### ISSUE TITLE
Complile error

### ISSUE THREAD

**Issue by polar1shu** [chuqingG/comp_exp#1]
This is a good work. But when I complied with it, I found it report '/home/hh21/BtreeComp/benchmark/benchmark.h:14:10: fatal error: art.hpp: No such file or directory.' Perhaps it miss files?

**Comment by polar1shu** [comment]
I know how to solve it. It needs to init submodule. But if I perform 'git submodule update --init,' it reports 'Permission denied (publickey).' error. So I must clone it for your links, and modify name to 'art'.

**Comment by chuqingG** [comment]
Hi, thanks for pointing that out, I've update the README to clarify it!

**Comment by chuqingG** [comment]
Hi, thanks for pointing that out, I've update the README to clarify it. Feel free to let me know if you have further questions!
